import matplotlib as mpl
from matplotlib import rc
import matplotlib.pyplot as plt
import numpy as np 
from pathlib import Path

rc('text', usetex=True)
ratio=0.0
fig_width_pt = 3*246.0  # Get this from LaTeX using \showthe\columnwidth
inches_per_pt = 1.0/72.27               # Convert pt to inch
golden_mean = ratio if ratio != 0.0 else (np.sqrt(5)-1.0)/2.0         # Aesthetic ratio
fig_width = fig_width_pt*inches_per_pt  # width in inches
fig_height = fig_width*golden_mean      # height in inches
fig_size =  [fig_width,fig_height]
params={'text.usetex' : True,
	'axes.labelsize': 24,
	'font.size': 24,
	'legend.fontsize': 24,
	'legend.handlelength': 1.5,
	'xtick.labelsize': 20,
	'ytick.labelsize': 20,
	'font.family' : 'serif',
	'axes.grid' : False,
	'lines.linewidth': 3,
	'lines.dashed_pattern': [2,1],
	'lines.dashdot_pattern': [5,2,1,1],
	'xtick.minor.visible': True,
	'ytick.minor.visible': True,
	'savefig.bbox': 'tight',
	'figure.figsize': fig_size}
plt.rcParams.update(params)

def plot_label(name, subscript=None, superscript=None, string_prefix=None, string_suffix=None):
	label=r"%s " %string_prefix if string_prefix is not None else r""
	label+='$'+name
	if subscript is not None:	label+='_{%s}' %subscript
	if superscript is not None:	label+='^{%s}' %superscript
	label+='$'
	if string_suffix is not None:	label+=' '+string_suffix
	return label

greek_labels={
	'alpha':r'$\alpha$',
	'beta':r'$\beta$',
	'gamma':r'$\gamma$',
	'Gamma':r'$\Gamma$',
	'delta':r'$\delta$',
	'Delta':r'$\Delta$',
	'epsilon':r'$\epsilon$',
	'zeta':r'$\zeta$',
	'eta':r'$\eta$',
	'theta':r'$\theta$',
	'Theta':r'$\Theta$',
	'iota':r'$\iota$',
	'kappa':r'$\kappa$',
	'lambda':r'$\lambda$',
	'Lambda':r'$\Lambda$',
	'mu':r'$\mu$',
	'nu':r'$\nu$',
	'xi':r'$\xi$',
	'omicron':r'$\omicron$',
	'pi':r'$\pi$',
	'rho':r'$\rho$',
	'sigma':r'$\sigma$',
	'Sigma':r'$\Sigma$',
	'tau':r'$\tau$',
	'upsilon':r'$\upsilon$',
	'phi':r'$\phi$',
	'Phi':r'$\Phi$',
	'chi':r'$\chi$',
	'psi':r'$\psi$',
	'Psi':r'$\Psi$',
	'Omega':r'$\Omega$',
	}

lalinference_labels={
	'm1':r'$m_1\,(\mathrm{M}_\odot)$',
	'm2':r'$m_2\,(\mathrm{M}_\odot)$',
	'mc':r'$\mathcal{M}\,(\mathrm{M}_\odot)$',
	'eta':r'$\eta$',
	'q':r'$q$',
	'mtotal':r'$M_\mathrm{total}\,(\mathrm{M}_\odot)$',
	'm1_source':r'$m_{1}^\mathrm{source}\,(\mathrm{M}_\odot)$',
	'm2_source':r'$m_{2}^\mathrm{source}\,(\mathrm{M}_\odot)$',
	'mtotal_source':r'$M_\mathrm{total}^\mathrm{source}\,(\mathrm{M}_\odot)$',
	'mc_source':r'$\mathcal{M}^\mathrm{source}\,(\mathrm{M}_\odot)$',
	'redshift':r'$z$',
	'mf':r'$M_\mathrm{final}\,(\mathrm{M}_\odot)$',
	'mf_source':r'$M_\mathrm{final}^\mathrm{source}\,(\mathrm{M}_\odot)$',
	'af':r'$a_\mathrm{final}$',
	'e_rad':r'$E_\mathrm{rad}\,(\mathrm{M}_\odot)$',
	'l_peak':r'$L_\mathrm{peak}\,(10^{56}\,\mathrm{ergs}\,\mathrm{s}^{-1})$',
	'spin1':r'$S_1$',
	'spin2':r'$S_2$',
	'a1':r'$a_1$',
	'a2':r'$a_2$',
	'a1z':r'$a_{1z}$',
	'a2z':r'$a_{2z}$',
	'theta1':r'$\theta_1\,(\mathrm{rad})$',
	'theta2':r'$\theta_2\,(\mathrm{rad})$',
	'phi1':r'$\phi_1\,(\mathrm{rad})$',
	'phi2':r'$\phi_2\,(\mathrm{rad})$',
	'chi_eff':r'$\chi_{\mathrm{eff}}$',
	'chi_tot':r'$\chi_\mathrm{total}$',
	'chi_p':r'$\chi_\mathrm{P}$',
	'tilt1':r'$t_1\,(\mathrm{rad})$',
	'tilt2':r'$t_2\,(\mathrm{rad})$',
	'costilt1':r'$\mathrm{cos}(t_1)$',
	'costilt2':r'$\mathrm{cos}(t_2)$',
	'iota':r'$\iota\,(\mathrm{rad})$',
	'cosiota':r'$\mathrm{cos}(\iota)$',
	'time':r'$t_\mathrm{c}\,(\mathrm{s})$',
	'time_mean':r'$<t>\,(\mathrm{s})$',
	'dist':r'$d_\mathrm{L}\,(\mathrm{Mpc})$',
	'ra':r'$\alpha$',
	'dec':r'$\delta$',
	'phase':r'$\phi\,(\mathrm{rad})$',
	'psi':r'$\psi\,(\mathrm{rad})$',
	'theta_jn':r'$\theta_\mathrm{JN}\,(\mathrm{rad})$',
	'costheta_jn':r'$\mathrm{cos}(\theta_\mathrm{JN})$',
	'beta':r'$\beta\,(\mathrm{rad})$',
	'cosbeta':r'$\mathrm{cos}(\beta)$',
	'phi_jl':r'$\phi_\mathrm{JL}\,(\mathrm{rad})$',
	'phi12':r'$\phi_\mathrm{12}\,(\mathrm{rad})$',
	'logl':r'$\mathrm{log}(\mathcal{L})$',
	'h1_end_time':r'$t_\mathrm{H}$',
	'l1_end_time':r'$t_\mathrm{L}$',
	'v1_end_time':r'$t_\mathrm{V}$',
	'h1l1_delay':r'$\Delta t_\mathrm{HL}$',
	'h1v1_delay':r'$\Delta t_\mathrm{HV}$',
	'l1v1_delay':r'$\Delta t_\mathrm{LV}$',
	'lambdat' :r'$\tilde{\Lambda}$',
	'dlambdat':r'$\delta \tilde{\Lambda}$',
	'lambda1' :r'$\lambda_1$',
	'lambda2':r'$\lambda_2$',
	'lam_tilde' :r'$\tilde{\Lambda}$',
	'dlam_tilde':r'$\delta \tilde{\Lambda}$',
	'calamp_h1' :r'$\delta A_{H1}$',
	'calamp_l1' :r'$\delta A_{L1}$',
	'calpha_h1' :r'$\delta \phi_{H1}$',
	'calpha_l1' :r'$\delta \phi_{L1}$',
	'polar_eccentricity':r'$\epsilon_{polar}$',
	'polar_angle':r'$\alpha_{polar}$',
	'alpha':r'$\alpha_{polar}$',
	'dchi0':r'$d\chi_0$',
	'dchi1':r'$d\chi_1$',
	'dchi2':r'$d\chi_2$',
	'dchi3':r'$d\chi_3$',
	'dchi4':r'$d\chi_4$',
	'dchi5':r'$d\chi_5$',
	'dchi5l':r'$d\chi_{5}^{(l)}$',
	'dchi6':r'$d\chi_6$',
	'dchi6l':r'$d\chi_{6}^{(l)}$',
	'dchi7':r'$d\chi_7$',
	'dxi1':r'$d\xi_1$',
	'dxi2':r'$d\xi_2$',
	'dxi3':r'$d\xi_3$',
	'dxi4':r'$d\xi_4$',
	'dxi5':r'$d\xi_5$',
	'dxi6':r'$d\xi_6$',
	'dalpha1':r'$d\alpha_1$',
	'dalpha2':r'$d\alpha_2$',
	'dalpha3':r'$d\alpha_3$',
	'dalpha4':r'$d\alpha_4$',
	'dalpha5':r'$d\alpha_5$',
	'dbeta1':r'$d\beta_1$',
	'dbeta2':r'$d\beta_2$',
	'dbeta3':r'$d\beta_3$',
	'dsigma1':r'$d\sigma_1$',
	'dsigma2':r'$d\sigma_2$',
	'dsigma3':r'$d\sigma_3$',
	'dsigma4':r'$d\sigma_4$',
	}	
